export const pets = [
    {
      name: "Pitter",
      location: "California, USA",
      gender: "Male",
      breed: "Pit Bull",
      age: "5 years",
      size: "Large",
      image: "/sample.png",
      isNew: true,
    },
    {
      name: "Hero",
      location: "Texas, USA",
      gender: "Male",
      breed: "DLH",
      age: "2 years",
      size: "Small",
      image: "/sample.png",
    },
    {
      name: "Magie",
      location: "Florida, USA",
      gender: "Female",
      breed: "Shiba Inu",
      age: "27 months",
      size: "Medium",
      image: "/sample.png",
    },
    {
      name: "Felix",
      location: "New York, USA",
      gender: "Female",
      breed: "Scottish",
      age: "9 months",
      size: "Small",
      image: "/sample.png",
    },
  ];